<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Pending Feedback Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 1px solid #000;
            padding-bottom: 8px;
        }

        .header h2 {
            margin: 0;
            font-size: 16px;
        }

        .meta {
            margin-bottom: 10px;
            font-size: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #333;
            color: #fff;
            font-weight: bold;
            padding: 6px;
            border: 1px solid #000;
            font-size: 10px;
        }

        td {
            padding: 6px;
            border: 1px solid #000;
            font-size: 10px;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 15px;
            text-align: center;
            font-size: 9px;
            border-top: 1px solid #000;
            padding-top: 5px;
        }
    </style>
</head>

<body>

<div class="header">
    <h2>Pending Feedback Report</h2>
</div>

<div class="meta">
    <strong>Course:</strong> {{ $course_name ?? 'All Courses' }} <br>
    <strong>Generated On:</strong> {{ $export_date }} <br>
    <strong>Total Records:</strong> {{ $students->count() }}
</div>

@if($students->count())

<table>
    <thead>
        <tr>
            <th width="4%">#</th>
            <th width="12%">Student</th>
            <th width="18%">Email</th>
            <th width="10%">Phone</th>
            <th width="8%">OT</th>
            <th width="14%">Course</th>
            <th width="14%">Session</th>
            <th width="10%">Faculty</th>
            <th width="10%">Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach($students as $i => $row)
        <tr>
            <td class="text-center">{{ $i + 1 }}</td>
            <td>{{ $row->student_name }}</td>
            <td>{{ $row->email }}</td>
            <td>{{ $row->contact_no }}</td>
            <td>{{ $row->generated_OT_code }}</td>
            <td>{{ $row->course_name }}</td>
            <td>{{ $row->subject_topic }}</td>
            <td>{{ $row->faculty_name ?? 'N/A' }}</td>
            <td>{{ date('d-m-Y', strtotime($row->from_date)) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

@else
    <p style="text-align:center;">No pending feedback records found.</p>
@endif

<div class="footer">
    Generated by {{ config('app.name') }} • This is a system generated report
</div>

</body>
</html>
