<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Family ID Card Requests Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 1px solid #000; padding-bottom: 8px; }
        .header h2 { margin: 0; font-size: 16px; }
        .meta { margin-bottom: 10px; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #122442; color: #fff; font-weight: bold; padding: 5px 6px; border: 1px solid #000; font-size: 9px; }
        td { padding: 5px 6px; border: 1px solid #ccc; font-size: 9px; }
        .text-center { text-align: center; }
        .footer { margin-top: 15px; text-align: center; font-size: 8px; border-top: 1px solid #000; padding-top: 5px; }
    </style>
</head>
<body>
<div class="header">
    <h2>Family ID Card Requests Report</h2>
</div>
<div class="meta">
    <strong>Type:</strong> {{ ucfirst($tab) }} Requests<br>
    <strong>Generated On:</strong> {{ $export_date }}<br>
    <strong>Total Records:</strong> {{ $requests->count() }}
</div>
@if($requests->count())
<table>
    <thead>
        <tr>
            <th width="5%">S.No.</th>
            <th width="12%">Request Date</th>
            <th width="15%">Employee Name</th>
            <th width="12%">Designation</th>
            <th width="12%">Department</th>
            <th width="12%">Member Name</th>
            <th width="8%">ID Type</th>
            <th width="12%">Valid From - To</th>
        </tr>
    </thead>
    <tbody>
        @foreach($requests as $i => $record)
        <tr>
            <td class="text-center">{{ $i + 1 }}</td>
            <td>{{ $record->created_at ? $record->created_at->format('d/m/Y') : '--' }}</td>
            <td>{{ $record->employee_name ?? $record->employee_id ?? '--' }}</td>
            <td>{{ $record->designation ?? '--' }}</td>
            <td>{{ $record->section ?? '--' }}</td>
            <td>{{ $record->name ?? '--' }}</td>
            <td>{{ $record->card_type ?? '--' }}</td>
            <td>{{ ($record->valid_from ? $record->valid_from->format('d/m/Y') : '--') }} - {{ ($record->valid_to ? $record->valid_to->format('d/m/Y') : '--') }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@else
<p style="text-align:center;">No family ID card requests found.</p>
@endif
<div class="footer">
    Generated by {{ config('app.name') }} &bull; System generated report
</div>
</body>
</html>
