/**
 * Stage 0 / S-4 — route discovery for the visual-regression baseline.
 *
 * Logs in, harvests every navigable route from the RBAC sidebar (including the
 * hidden tab panes, which hold most of the menu tree), then writes a
 * DETERMINISTIC, committed route list to routes.json.
 *
 * Why discovery instead of a hand-written list: the sidebar is database-driven
 * (SidebarNavResolver + MenuRouteMatcher), so a hand-written list would drift
 * from what users can actually reach. Why a committed file instead of crawling
 * at capture time: the baseline must screenshot the SAME routes every run.
 *
 * Guarded behind E2E_DISCOVER=1 so a normal test run can never silently
 * regenerate the route list the baseline is pinned to.
 *
 *   E2E_DISCOVER=1 E2E_USERNAME=... E2E_PASSWORD=... \
 *     npx playwright test tests/e2e/visual/discover-routes.spec.js --project=chrome
 */

const fs = require('fs');
const { test, expect } = require('@playwright/test');
const { login, ROUTES_FILE } = require('./_helpers');

const MAX_ROUTES = parseInt(process.env.E2E_MAX_ROUTES || '60', 10);

// Never screenshot these — they mutate state or end the session.
const EXCLUDE = /logout|signout|delete|destroy|remove|export|download|print|pdf|excel|csv|\.(pdf|xlsx|csv|zip)$/i;

test.describe('S-4 route discovery', () => {
    test.skip(!process.env.E2E_DISCOVER, 'Set E2E_DISCOVER=1 to regenerate routes.json');
    test.skip(({}, testInfo) => testInfo.project.name !== 'chrome', 'Discovery runs once, on chrome');

    test('harvest sidebar routes into routes.json', async ({ page, baseURL }) => {
        test.setTimeout(240 * 1000);

        const landing = await login(page, baseURL);
        const origin = new URL(page.url()).origin;

        // Collect every anchor in the document, including those inside hidden
        // tab panes — querySelectorAll reaches hidden nodes, so we do not need
        // to click through the five RBAC panes (and risk changing state).
        const hrefs = await page.evaluate((originArg) => {
            return Array.from(document.querySelectorAll('a[href]'))
                .map((a) => a.href)
                .filter((h) => h && h.startsWith(originArg))
                .filter((h) => !h.includes('#'))
                .filter((h) => !h.startsWith('javascript:'));
        }, origin);

        const cleaned = Array.from(new Set(hrefs))
            .map((h) => new URL(h).pathname)
            .filter((p) => p && p !== '/')
            .filter((p) => !EXCLUDE.test(p))
            // Skip routes with numeric ids — record-specific pages are unstable
            // baselines (the record may be edited or deleted between runs).
            .filter((p) => !/\/\d{2,}(\/|$)/.test(p))
            .sort();

        expect(cleaned.length, 'Sidebar yielded no navigable routes — is the account permissioned?')
            .toBeGreaterThan(0);

        // Spread the cap across modules (first path segment) so 60 routes cover
        // many modules rather than 60 pages of whichever module sorts first.
        const byModule = new Map();
        for (const p of cleaned) {
            const mod = p.split('/').filter(Boolean)[0] || 'root';
            if (!byModule.has(mod)) byModule.set(mod, []);
            byModule.get(mod).push(p);
        }

        const modules = Array.from(byModule.keys()).sort();
        const picked = [];
        let depth = 0;
        while (picked.length < MAX_ROUTES) {
            let addedThisPass = false;
            for (const mod of modules) {
                const list = byModule.get(mod);
                if (depth < list.length) {
                    picked.push(list[depth]);
                    addedThisPass = true;
                    if (picked.length >= MAX_ROUTES) break;
                }
            }
            if (!addedThisPass) break;   // every module exhausted
            depth += 1;
        }

        // The landing/dashboard page is the most-viewed screen; pin it first.
        const landingPath = new URL(landing).pathname;
        const ordered = [landingPath, ...picked.filter((p) => p !== landingPath)]
            .slice(0, MAX_ROUTES);

        const payload = {
            _comment: 'Generated by discover-routes.spec.js (Stage 0 / S-4). '
                + 'Committed so the visual baseline pins the SAME routes every run. '
                + 'Regenerate with E2E_DISCOVER=1.',
            generatedFrom: origin,
            totalDiscovered: cleaned.length,
            moduleCount: modules.length,
            captured: ordered.length,
            routes: ordered,
        };

        fs.writeFileSync(ROUTES_FILE, JSON.stringify(payload, null, 2) + '\n', 'utf8');

        console.log(`\n  discovered ${cleaned.length} routes across ${modules.length} modules`);
        console.log(`  captured ${ordered.length} -> ${ROUTES_FILE}\n`);
    });
});
