<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Enrolled Students Report - {{ $courseName }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            font-size: 11px; 
            margin: 0;
            padding: 10px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 15px; 
            border-bottom: 2px solid #333; 
            padding-bottom: 10px; 
        }
        .header h2 { 
            margin: 0; 
            color: #333; 
            font-size: 18px; 
        }
        .header p { 
            margin: 3px 0; 
            color: #666; 
        }
        .summary-box {
            background: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 8px;
            margin-bottom: 10px;
            font-size: 10px;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 10px; 
        }
        table th { 
            background-color: #e6423d;
            color: white;
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
            font-weight: bold; 
            font-size: 11px;
        }
        table td { 
            border: 1px solid #ddd; 
            padding: 6px; 
            font-size: 10px;
        }
        .status-active {
            color: green;
            font-weight: bold;
        }
        .status-inactive {
            color: red;
            font-weight: bold;
        }
        .footer { 
            margin-top: 20px; 
            text-align: center; 
            color: #666; 
            font-size: 9px; 
            border-top: 1px solid #ddd; 
            padding-top: 10px; 
        }
        .text-center { text-align: center; }
        .text-left { text-align: left; }
        .text-right { text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Enrolled Students Report</h2>
        <p><strong>Course:</strong> {{ $courseName }}</p>
        <p><strong>Generated On:</strong> {{ $exportDate }}</p>
        <p><strong>Total Students:</strong> {{ $totalCount }}</p>
    </div>

    @if($enrollments->count() > 0)
        <table>
            <thead>
                <tr>
                    <th width="5%" class="text-center">#</th>
                    <th width="25%" class="text-left">Student Name</th>
                    <th width="20%" class="text-left">Email</th>
                    <th width="15%" class="text-left">Phone</th>
                    <th width="15%" class="text-center">OT Code</th> <!-- Changed from Course to OT Code -->
                    <th width="10%" class="text-center">Enrollment Date</th>
                    <th width="5%" class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($enrollments as $index => $enrollment)
                    @php
                        $student = $enrollment->studentMaster;
                        $course = $enrollment->course;
                    @endphp
                    <tr>
                        <td class="text-center">{{ $index + 1 }}</td>
                        <td class="text-left">
                            {{ $student ? trim(($student->first_name ?? '') . ' ' . ($student->last_name ?? '')) : 'N/A' }}
                        </td>
                        <td class="text-left">{{ $student->email ?? 'N/A' }}</td>
                        <td class="text-left">{{ $student->contact_no ?? 'N/A' }}</td>
                        <td class="text-center">
                            <!-- Display OT Code instead of Course -->
                            {{ $student->generated_OT_code ?? 'N/A' }}
                        </td>
                        <td class="text-center">
                            {{ $enrollment->created_date ? date('d M Y', strtotime($enrollment->created_date)) : 'N/A' }}
                        </td>
                        <td class="text-center">
                            @if($enrollment->active_inactive)
                                <span class="status-active">Active</span>
                            @else
                                <span class="status-inactive">Inactive</span>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666; font-size: 14px;">
            No enrolled students found for the selected criteria.
        </div>
    @endif

    <div class="footer">
        <p>Generated by Sargam | Lal Bahadur System •</p>
        <p>Report ID: ENR-{{ date('Ymd-His') }}</p>
    </div>
</body>
</html>