<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Vehicle Pass Requests Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 1px solid #000; padding-bottom: 8px; }
        .header h2 { margin: 0; font-size: 16px; }
        .meta { margin-bottom: 10px; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #122442; color: #fff; font-weight: bold; padding: 5px 6px; border: 1px solid #000; font-size: 9px; }
        td { padding: 5px 6px; border: 1px solid #ccc; font-size: 9px; }
        .text-center { text-align: center; }
        .footer { margin-top: 15px; text-align: center; font-size: 8px; border-top: 1px solid #000; padding-top: 5px; }
    </style>
</head>
<body>
<div class="header">
    <h2>Vehicle Pass Requests Report</h2>
</div>
<div class="meta">
    <strong>Type:</strong> {{ ucfirst($tab) }} Requests<br>
    <strong>Generated On:</strong> {{ $export_date }}<br>
    <strong>Total Records:</strong> {{ $passes->count() }}
</div>
@if($passes->count())
<table>
    <thead>
        <tr>
            <th width="5%">S.No.</th>
            <th width="18%">Employee Name</th>
            <th width="12%">Vehicle Pass No.</th>
            <th width="12%">Vehicle Type</th>
            <th width="12%">Vehicle Number</th>
            <th width="15%">Requested Date</th>
            <th width="10%">Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($passes as $i => $record)
        <tr>
            <td class="text-center">{{ $i + 1 }}</td>
            <td>{{ $record->display_name }}</td>
            <td>{{ $record->vehicle_req_id ?? '--' }}</td>
            <td>{{ $record->vehicleType->vehicle_type ?? '--' }}</td>
            <td>{{ $record->vehicle_no ?? '--' }}</td>
            <td>{{ $record->created_date ? $record->created_date->format('d/m/Y H:i') : '--' }}</td>
            <td>
                @if($record->vech_card_status == 1)
                    Pending
                @elseif($record->vech_card_status == 2)
                    Approved
                @else
                    Rejected
                @endif
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@else
<p style="text-align:center;">No vehicle pass requests found.</p>
@endif
<div class="footer">
    Generated by {{ config('app.name') }} &bull; System generated report
</div>
</body>
</html>
